### ISSUE TITLE
Redirect on manwha

### ISSUE THREAD

**Issue by KarhnO** [Tyson3101/Redirect-Blocker#10]
So on the website https://standardsofreincarnation.com/manga/standard-of-reincarnation-chapter-1/
Sometimes when I click next chapter it opens up the next chapter as well as another redirect to a porn site.

**Comment by Tyson3101** [comment]
Hi thanks for the this,
I wasn't able to replicate the issue. I did get a popup appear of the .webp of the manga, but the redirect blocker was able to block that. 
Are you able to further describe what happens, in terms what kinda redirect it is, like if it takes you to a new tab of the pornsite? or etc?

**Comment by KarhnO** [comment]
yea so when i was reading i do not know if the porn site became the tab and
created a new one for the next chapter or vice versa.
I can say when it did happen a new tab would get added and the porn site
was on the left side of the chapter.

It didn't happen all the time either and when I tried replicating it
without the blocker it didn't even happen I don't know why. Maybe something
about how long you spend on the browser or it takes extra time to load I
have no clue.
As you can tell I know jack shit about redirects and websites.
