### ISSUE TITLE
Port to Mozilla Firefox

### ISSUE THREAD

**Issue by thatalb3rt** [Tyson3101/Redirect-Blocker#11]
Too bad it's not on Firefox. It would've been perfect since there are no alternatives for it. I tried porting it myself to Firefox using their built-in porting tool but it says it's an error with the manifest. Will you port it on Firefox eventually?

**Comment by Tyson3101** [comment]
Hey,
Porting to Firefox has never really been on my mind, as I have never worked with it.
But I have just had a look, and porting it doesn't seem to complicated so when I have time I'll see if I can

Or if you ever do find or get a port to work, let me know.

**Comment by thatalb3rt** [comment]
Thanks a lot man. If i can do it i will let you know.

**Comment by Tyson3101** [comment]
Hey, I am just uploaded the extension to firefox, I have lightly tested it, and it seems to work fine for me, but probably may have some issues.
https://addons.mozilla.org/en-US/firefox/addon/redirectblocker/

I do want to apologize, as porting it was easier than expected, and I should've got around to do it quicker, 
But do let me know if you face any issues, and will do my best to fix them.

**Comment by thatalb3rt** [comment]
Hey man, thanks a lot! I will test it and if there are issues i will tell you. You really don't have to apologize since it's your work and it's free so you could take all the time you needed :)
