### ISSUE TITLE
Links not saving when i enter them and click off the extension

### ISSUE THREAD

**Issue by Zaxhy** [Tyson3101/Redirect-Blocker#16]
When I try to add links to the saved links, it erases right after I click off the extension. I have tried uninstalling and reinstalling but didn't help. Is there a fix for this?

**Comment by Zaxhy** [comment]
https://github.com/user-attachments/assets/2dbc9ffe-85a9-4573-b0ca-659a7354bb29

(video of the issue because maybe I'm just doing something wrong)

**Comment by Tyson3101** [comment]
Hey thanks for the issue,
The problem is that it doesn't register it as a link without the "https://..."

I should probably allow saving urls as you do without, but for now that should be the solution.

**Comment by Zaxhy** [comment]
That worked. Thanks, and it might be helpful to add a little sub-note to include https:// in links.

**Comment by Tyson3101** [comment]
Yeah definitely thanks for the tip, glad it worked out in the end!
