### ISSUE TITLE
rdb issue

### ISSUE THREAD

**Issue by mongoread** [Tyson3101/Redirect-Blocker#4]
i'm noticing that rdb needs to constantly be turned on ? really annoying. for saved urls, i added https://* idk if that's working very well or not. idk why it wouldn't be auto on whenever you turn the thing on- not for each TAB, but on the entire browser. reinstall, reboot. same issues.

**Comment by Tyson3101** [comment]
Hi, the reason it is not always on is I don't see what the use case would be for that
For example, the reason I first made this extension was to deal with the annoying redirects of streaming sites and etc, which doesn't require it to be constantly on as it only blocks redirects on that tab/site

With that, I want to ask what you want it constantly on for?
But if you do have a case for when you want it on constantly then that is something I can add

**Comment by mongoread** [comment]
I'll turn it on when I turn on my pc, it works great. On the same site, tab, page, even, at times it will turn itself off. On many streaming sites, like TV shows, they're only ~15 minutes long. If you click on the site to watch the next episode, etc., more pop-ups.
On some sports TV sites, same, but not as bad as the TV show streaming sites.
The app works very well, I appreciate it and your work.
I'll also suggest to add a way to pay you, for those enjoying the app, it's worth it.
Thanks, have a great day.
Patrick

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mongoread** [comment]
Also, if I didn't state this clearly. It's trash dependent, sometimes? Turn on, works on that tab, switch tabs, then need to turn it on again. Idk if it's tabs, or timing out as you said-
Thanks

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tyson3101** [comment]
Oh I see what you mean, the timing out/it turning off is something that shouldn't happen.
If you turn it on it should stay on always for that specific tab (Unless you turn it off, delete tab, etc).
From the times I have used it and me just testing it again now, I don't seem to have it timing out.

By you saying it turns off, does it say it is off, or it just stops working and doesn't block the redirects/popups?
And do you have an estimate of the time it takes to timeout/stop working?

Thanks and I'm glad you enjoy the extension

**Comment by mongoread** [comment]
Hi Tyson,

I'm not sure. I always have lots of tabs open, and switch around frequently whether I'm watching a TV show, playing a game, or doing research.

For me, if the app turned on, and worked for every tab, without doing anything else for that session while using the browser, that would be ideal.

Popups suck, this app helps a lot.

Thanks for your hard work,

Patrick

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tyson3101** [comment]
Hi, sorry I totally just forgot to respond to your message, 
But.. I have just uploaded an update which adds a feature to toggle the extension for all tabs

I hope you find it works well, and makes the extension more helpful
Sorry for the long wait in reply and for this update

And if you find any issues please let me know!

**Comment by mongoread** [comment]
Hi Tyson,

All tabs. Well done, that should be nice, helpful.

I'll keep you in mind, send you some $ for your help in the near future.

Thanks again, have a blessed day.

Patrick


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
