### ISSUE TITLE
RDB, Auto On

### ISSUE THREAD

**Issue by Shad0plex** [Tyson3101/Redirect-Blocker#6]
I saw on a review in the Chrome web store that you added the feature "auto on" by default. However, I don't see that option anywhere.
IMO, it would be easier to just turn it off or add a website to a whitelist when needed, especially given the way people encounter redirects on a simple Google search.  
Thank you

**Comment by Tyson3101** [comment]
Hi thanks for the issue as I finally now understand what the review was meaning. 

The reason of it not having this feature and not fully understanding of it at first was when I made this extension it was just to be able to block the redirects on the ~~illegal~~ sports sites I watched. And was the main use case of the extension for me

But now with the extension growing, and the use cases and redirects people face like what you mentioned, I see why this is a needed feature I will add

**Comment by Shad0plex** [comment]
Awesome to hear. Thank you!
