### ISSUE TITLE
Temporary Full Redirect Block Feature/Extension

### ISSUE THREAD

**Issue by Bluscream** [Tyson3101/Redirect-Blocker#8]
PLEASE add a toggle to temporarily block all automated page redirects
like https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#html_redirections and other methods
either in this addon or ideally a seperate one

**Comment by Tyson3101** [comment]
Hey thanks for this, I will have a look into how the extension could block those methods, as I do see how these can be beneficial, especially with the extension growing in use cases.
